version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - echo "Setting environment variables..."
      - export AWS_DEFAULT_REGION=us-east-1
      - echo $AWS_DEFAULT_REGION
      - REPOSITORY_URI=863518422262.dkr.ecr.us-east-1.amazonaws.com/ecr-iris-repo
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Installing dependencies..."
      - pip install -r src/requirements.txt

  build:
    commands:
      - echo "Training the model..."
      - python src/train.py
      - echo "Model training complete."
      - echo "Building the Docker image..."
      - docker build -t ml-iris-app .
      - echo "Docker image created successfully."
      - echo "Tagging the Docker image..."
      - docker tag ml-iris-app $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "Deploying the application to EC2..."
      -#  chmod +x scripts/deploy.sh
      - #./scripts/deploy.sh
      - echo "Deployment completed."

artifacts:
  files:
    - '**/*'
