version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - AWS_DEFAULT_REGION=us-east-1
      - echo $AWS_DEFAULT_REGION
      - REPOSITORY_URI=863518422262.dkr.ecr.us-east-1.amazonaws.com/ecr-iris-repo:latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - AWS_ACCESS_KEY_ID=AKIA4SDNVOT3P6OBZPV5
      - AWS_SECRET_ACCESS_KEY=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

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t ml-iris-app .
      - echo "Docker image got created successfully"
      - echo "Tagging the Docker image..."
      - docker tag ml-iris-app 863518422262.dkr.ecr.us-east-1.amazonaws.com/ecr-iris-repo:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push 863518422262.dkr.ecr.us-east-1.amazonaws.com/ecr-iris-repo:latest
      - echo "Deploy the Docker image to Elastic Kubernetes"
      - echo "docker pusehd to ECR"
     
artifacts:
  files:
    - '**/*'
