version: 0.2

phases:
  install:
      runtime-versions:
      docker: 25
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - AWS_DEFAULT_REGION=us-east-1
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335461340.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=730335461340.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - echo Build started on `date`
      - echo Building the Docker image...           
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest	    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing the docker image
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 730335461340.dkr.ecr.us-east-1.amazonaws.com/iris-model:latest
      # Optionally, you can include steps to deploy the image or update configurations here.

artifacts:
  files:
    - '**/*'
