apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-code-deploy-app
  labels:
    app: iris-code-deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-code-deploy-app
  template:
    metadata:
      labels:
        app: iris-code-deploy-app
    spec:
      containers:
      - name: iris-code-deploy-container
        image: 863518422262.dkr.ecr.us-east-1.amazonaws.com/ecr-iris-repo
        ports:
        - containerPort: 80
